### ISSUE TITLE
Notice

### ISSUE THREAD

**Issue by PtPrashantTripathi** [chirag127/Gitanest#1]
https://github.com/chirag127/Gitanest/blob/79f8280197253d0235a128bf362825c3d7efb578/script.js#L2

Kindly don't push your api key in open source git

Otherwise you will be permanently banned from our api

Sincerely
@ptprashanttripathi
(Bhagavad Gita API Admin)

**Comment by chirag127** [comment]
Make it private?

**Comment by chirag127** [comment]
@PtPrashantTripathi seems like your api is now public and don't need an api key?

**Comment by chirag127** [comment]
So, I'm making this repository public too.

**Comment by PtPrashantTripathi** [comment]
Sure buddy no issue
